Prateek KK
20BEC0102

In [ ]:
import numpy as np
import pandas as pd

# Task 1

#### Method 1

In [13]:
S1=pd.Series(np.random.rand(4))
S2=pd.Series(np.random.rand(4))
S3=pd.Series(np.random.rand(4))
S4=pd.Series(np.random.rand(4))

In [21]:
print(S1,'\n \n',S2,'\n \n',S3,'\n \n',S4)

0    0.024399
1    0.418461
2    0.067345
3    0.595618
dtype: float64 
 
 0    0.374406
1    0.572035
2    0.013223
3    0.468929
dtype: float64 
 
 0    0.762778
1    0.353837
2    0.573157
3    0.009400
dtype: float64 
 
 0    0.954671
1    0.305358
2    0.212058
3    0.339082
dtype: float64


In [18]:
df=pd.DataFrame([S1,S2,S3,S4])

In [20]:
df

0         1         2         3
0  0.024399  0.418461  0.067345  0.595618
1  0.374406  0.572035  0.013223  0.468929
2  0.762778  0.353837  0.573157  0.009400
3  0.954671  0.305358  0.212058  0.339082

#### Method 2

In [22]:
random_data=np.random.randint(0,200,size=(4,4))

In [23]:
print(random_data)

[[ 29  83 115 150]
 [196  93  38  64]
 [ 10 109  24 189]
 [187 152  37 168]]


In [24]:
df2=pd.DataFrame(random_data)

In [25]:
df2

0    1    2    3
0   29   83  115  150
1  196   93   38   64
2   10  109   24  189
3  187  152   37  168

# Task 2

#### Method 1

In [26]:
df.columns=['Random value 1','Random value 2','Random value 3','Random value 4']

In [27]:
df

Random value 1  Random value 2  Random value 3  Random value 4
0        0.024399        0.418461        0.067345        0.595618
1        0.374406        0.572035        0.013223        0.468929
2        0.762778        0.353837        0.573157        0.009400
3        0.954671        0.305358        0.212058        0.339082

#### Method 2

In [28]:
df3=pd.DataFrame(random_data,columns=['Random value 1','Random value 2','Random value 3','Ranodm value 4'])

In [29]:
df3

Random value 1  Random value 2  Random value 3  Ranodm value 4
0              29              83             115             150
1             196              93              38              64
2              10             109              24             189
3             187             152              37             168

# Task 3

In [30]:
df.describe(include='all')

Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.529064        0.412423        0.216446        0.353257
std          0.414073        0.116057        0.252186        0.252030
min          0.024399        0.305358        0.013223        0.009400
25%          0.286905        0.341717        0.053815        0.256661
50%          0.568592        0.386149        0.139701        0.404005
75%          0.810751        0.456854        0.302332        0.500601
max          0.954671        0.572035        0.573157        0.595618

In [31]:
df3.describe(include='all')

Random value 1  Random value 2  Random value 3  Ranodm value 4
count         4.00000        4.000000        4.000000        4.000000
mean        105.50000      109.250000       53.500000      142.750000
std          99.67447       30.445306       41.492971       54.865745
min          10.00000       83.000000       24.000000       64.000000
25%          24.25000       90.500000       33.750000      128.500000
50%         108.00000      101.000000       37.500000      159.000000
75%         189.25000      119.750000       57.250000      173.250000
max         196.00000      152.000000      115.000000      189.000000

# Task 4

In [32]:
# making one of the values null

df['Random value 1'][2]=np.nan

In [33]:
df

Random value 1  Random value 2  Random value 3  Random value 4
0        0.024399        0.418461        0.067345        0.595618
1        0.374406        0.572035        0.013223        0.468929
2             NaN        0.353837        0.573157        0.009400
3        0.954671        0.305358        0.212058        0.339082

In [34]:
df.isnull()

Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2            True           False           False           False
3           False           False           False           False

In [36]:
df.isnull().sum()

Random value 1    1
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

In [ ]:
# Checking the data type of columns

In [37]:
df['Random value 1'].dtype

dtype('float64')

In [39]:
df3['Random value 2'].dtype

dtype('int32')

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Random value 1  3 non-null      float64
 1   Random value 2  4 non-null      float64
 2   Random value 3  4 non-null      float64
 3   Random value 4  4 non-null      float64
dtypes: float64(4)
memory usage: 256.0 bytes


In [40]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random value 1  4 non-null      int32
 1   Random value 2  4 non-null      int32
 2   Random value 3  4 non-null      int32
 3   Ranodm value 4  4 non-null      int32
dtypes: int32(4)
memory usage: 192.0 bytes


# Task 5

In [41]:
## Using loc method

df.loc[:,'Random value 2':'Random value 3']

Random value 2  Random value 3
0        0.418461        0.067345
1        0.572035        0.013223
2        0.353837        0.573157
3        0.305358        0.212058

In [44]:
## Using iloc method

df.iloc[:,1:3]

Random value 2  Random value 3
0        0.418461        0.067345
1        0.572035        0.013223
2        0.353837        0.573157
3        0.305358        0.212058